### ISSUE TITLE
YouTube ads on first load

### ISSUE THREAD

**Issue by skunkfox** [ghostery/adblocker#2757] opened 2022-08-14 16:29 UTC
I am using the following video as a test: https://www.youtube.com/watch?v=-t9XZgk6kNY

I discovered when using the [Vieb browser](https://vieb.dev/) that I was seeing ads in the following video. I know that I don't see ads in Brave or Firefox with ublock origin, and I know that Vieb using ghostery's adblock. Curious, I fired up adblocker-electron-example and loaded the page. Sure enough, the same ads appeared.

However, after pausing the video, if I then search YouTube for the same video, it plays without ads! This doesn't occur in Vieb, so I opened up the developer console in both Vieb and adblocker-electron-example. I'm noticing that when I load the YouTube video for both for the first time, one of the items that gets blocked is something called '56-y-ORG.js', request url: 'https://tpc.googlesyndication.com/sodar/56-y-0RG.js'. Maybe it has something to do with cross-origin? On subsequent Vieb loads that network request continues to appear, but on subsequent adblocker-electron-example loads, it does not.

I'd love to help debug this issue and improve adblocking, but I'm still very new to electron and node.js. I was wondering if there is someone I can contact on Telegram or Discord or Matrix to bounce questions off of, since I'd really like to help as much as I can.

**Comment by remusao** [comment] 2022-08-28 20:35
Hi @skunkfox,

Thanks for reaching out. One reason the result with Vieb and `adblocker-electron-example` can differ is if they use different versions of the rules/resources. I see the rules are vendored in https://github.com/Jelmerro/Vieb/tree/master/app/blocklists and are manually updated. Maybe we could try with the latest version of all files.

The `adblocker-electron-example` project also loads more blocklists by default (so maybe would it be good to try to load the uBlock Origin filters there as well). You can check `adsLists` and `adsAndTrackingLists` here: https://github.com/ghostery/adblocker/blob/master/packages/adblocker/src/fetch.ts#L55

In general, even in a browser, blocking YouTube ads is tricky and there is often a race between ads loading and how fast the adblocker can inject the scripts in the page. In particular, whenever there is a round-trip between the page content and the adblocker (e.g. using `ipcMain.on("get-cosmetic-filters")`), it might already be too late (sometimes the ads will be blocked, sometimes not, depending on if injection is fast enough). I am not sure if that's possible on Electron but in the browser we can listen to navigation events and pro-actively inject scripts to pages from the main process (which works better).

Cc @Jelmerro who might be able to provide more insights there.

I hope that helps,

**Comment by Jelmerro** [comment] 2022-08-28 21:18
@remusao The lists are included by default, but can also optionally be updated on startup, which to my knowledge most users are aware of and using (from what I read in comments and reddit posts). I am looking for more lists to include by default, but I do see a lot of ads passing through with easylist and easyprivacy that are not there when using ublock origin. If that is due to missing lists, better filtering by ublock or by an incorrect implementation in Vieb is not known to me, but I highly suspect it's a combination of missing lists and ublock origin having better adblocking. My main question is: What can I provide in terms of data or code that would help with debugging the cause of this issue, so that we can block ads on Youtube more reliably?

**Comment by remusao** [comment] 2022-08-29 18:01
Thanks for the quick feedback @Jelmerro. I would probably start by trying to all the same list as default uBlock Origin in Vieb by default and then check again if ads are still going through. 

I think the following would be a good starting point (including `adsLists` and `adsAndTrackingLists`): https://github.com/ghostery/adblocker/blob/master/packages/adblocker/src/fetch.ts#L55

**Comment by Jelmerro** [comment] 2022-08-30 21:01
How often are these lists updated in the repo, and/or can we fetch these lists directly from easylist/ublock/peter instead? I can't find the urls for all of them, only a few. Besides that, my biggest worry is that it's not the lists, but the custom loading system I had to make due to Electron only allowing a single onBeforeRequest listener at a time.
When creating a new session `newSess` I do this:
![image](https://user-images.githubusercontent.com/1696674/187541133-9bd0a9b6-d8e6-45af-a766-712905b266e0.png)
And also this:
![image](https://user-images.githubusercontent.com/1696674/187541338-f0bfca72-2068-4edf-86f9-a016f6be6edb.png)
The adblockerPreload is the worst part of this, since it's not exported, I had to do this:
![image](https://user-images.githubusercontent.com/1696674/187541472-8d33e750-6f11-4bbe-9271-af9f59153b35.png)
Which I would like to avoid, but for now I will try to add more lists, which is in line with what I recommend my users who complain about Youtube ads, though I'm skeptical if they can really be blocked properly at all. Code can be found [in the Vieb repo in the index.js file](https://github.com/Jelmerro/Vieb/blob/master/app/index.js) in case you are curious to check it out yourself. Thanks for looking into this.

**Comment by remusao** [comment] 2022-08-30 21:47
The lists are being updated continuously, but on this versions mirrored on this repository are updated at most once per day (and that's if I merge the PR...). It's a good idea to pull from the source directly if you can. The URLs can be found here: https://github.com/ghostery/adblocker/blob/master/packages/adblocker/assets/update.js#L27

I agree with you that blocking YouTube ads is particularly challenging (even in the browser, where all capabilities are available to the adblocker). And Electron is a bit more limited in some ways. But it can probably be made to work well enough. I don't have lots of time to dedicate to this issue at the moment unfortunately but happy to help however I can.

To get the preload script path, did you try something like that? https://github.com/ghostery/adblocker/blob/master/packages/adblocker-electron/adblocker.ts#L18

**Comment by Jelmerro** [comment] 2022-08-30 22:02
Thanks for the list of urls, I am now only missing the `resources` file still.

Yes, I need the listener myself for redirecting urls, but it seems to work fine indeed, so not something that really needs changing. I'm mostly concerned about the preload.

As for the preload path, yes I had that before, but since moving to webpack I had to do it as a string instead of using `require.resolve`, as that will not resolve correctly after building it with webpack. I ran out of ideas to try to get the path in a way that would satisfy webpack, so I had to use a fixed path, but I imagine that this path does not change often, and if it does, the build will fail anyway.

**Comment by Jelmerro** [comment] 2022-08-30 22:04
My bad, the resources file is in there above the line you linked, but it's coming from a cliqz cdn indirectly, by fetching some metadata first instead of the original location (if any). I would rather get it from the source if possible.

**Comment by remusao** [comment] 2022-08-31 08:26
There is no source per say because the resources file has to be transformed to be compatible with Cliqz' adblocker. So your best bet is to use this one from the CDN. On the other hand it does not change very often so it might not be a big issue.

**Comment by Jelmerro** [comment] 2022-08-31 12:22
I can see the ads on Youtube even when adding all the lists mentioned, which is in line with @skunkfox's test results, because they also had it with the adblocker-electron-example. Any chance it's not the fault of the lists, but missing support for some syntax in the ublock lists?

**Comment by remusao** [comment] 2022-08-31 12:49
I don't think so, because `@cliqz/adblocker` is perfectly able to block ads in a browser context. I would suspect that Electron's API (or Electron wrapper) is not on par with the browser support and something is either missing, or behaving in a way that is not allowing YouTube ads to be blocked. We'd need to investigate to figure this out. One usual suspect (especially on Electron) is the injection of scriptlets in pages. There were issues in the past with sandboxing, etc. so we should make sure that the injection works as expected.

**Comment by skunkfox** [comment] 2022-09-03 08:01
I'm so glad to see that there has been activity on this issue.

What can I, a programmer but JS and electron newb, do to help?

**Comment by remusao** [comment] 2022-09-03 14:13
@skunkfox thanks for offering your help! I think one first step would be to verify that scripts are injected in pages by the ElectronBlocker. This happens here: https://github.com/ghostery/adblocker/blob/master/packages/adblocker-electron/adblocker.ts#L271

There were updates in the past with Electron which prevented the scripts from being injected in page content (sandboxing, etc.). So first step would be to make sure that's not the case. Philipp recently added some debugging code for the WebExtensionBlocker here: https://github.com/ghostery/adblocker/blob/d8cb2bbf7cef2c4459dddb90e347d697e429ba7c/packages/adblocker-webextension/adblocker.ts#L623

We could do something similar in ElectronBlocker to add a `console.error`, visit YouTube and expect to see these logs in the console logs of the page. If they are not seen, then maybe the scripts are not injected correctly.

Depending on the result of this investigation we can think of next steps (if the injection does not work, there might be options in Electron that we can tweak, etc.).

All of the above should be possible to test by using the adblock-electron-example project locally.

**Comment by skunkfox** [comment] 2022-09-04 11:56
> @skunkfox thanks for offering your help! I think one first step would be to verify that scripts are injected in pages by the ElectronBlocker. This happens here: https://github.com/ghostery/adblocker/blob/master/packages/adblocker-electron/adblocker.ts#L271
> 
> There were updates in the past with Electron which prevented the scripts from being injected in page content (sandboxing, etc.). So first step would be to make sure that's not the case. Philipp recently added some debugging code for the WebExtensionBlocker here:
> 
> https://github.com/ghostery/adblocker/blob/d8cb2bbf7cef2c4459dddb90e347d697e429ba7c/packages/adblocker-webextension/adblocker.ts#L623
> 
> We could do something similar in ElectronBlocker to add a `console.error`, visit YouTube and expect to see these logs in the console logs of the page. If they are not seen, then maybe the scripts are not injected correctly.
> 
> Depending on the result of this investigation we can think of next steps (if the injection does not work, there might be options in Electron that we can tweak, etc.).
> 
> All of the above should be possible to test by using the adblock-electron-example project locally.

Wow, thanks for the quick response!

So believe it or not I **just** got really sick and test positive for COVID. So I'm mostly going to be sleeping for these next few days. However, I look forward to helping debug after I get better. Just a warning that it may be a few days.

**Comment by remusao** [comment] 2022-09-04 15:37
Get well soon!

**Comment by skunkfox** [comment] 2022-09-10 13:32
I am slowly recovering from COVID. I added some debug code.

```
  private injectScripts(sender: Electron.WebContents, script: string): void {
    sender.executeJavaScript(script);
    console.error("[ADBLOCKER-DEBUG] - [injectScripts] - ", JSON.stringify(script));
  }

  private injectStyles(sender: Electron.WebContents, styles: string): void {
    if (styles.length > 0) {
      console.error("[ADBLOCKER-DEBUG] - [injectStyles] - ", JSON.stringify(styles));
      sender.insertCSS(styles, {
        cssOrigin: 'user',
      });
    }
```
It looks like these functions are being called when I visit the YouTube video and see ads. I can paste the console.error messages if you'd like, but they are enormous.

**Comment by remusao** [comment] 2022-09-15 10:32
Great to hear that you're doing better. Thanks for looking into this issue, that's a great start. So at least we know that scriplets and styles are correctly returned for youtube.com. I think the next step would be to check that the injection in the page happens as expected. One way would be to wrap the scripts injected with some debugging code to see its effect in page. You could try something like this maybe? https://github.com/ghostery/adblocker/blob/master/packages/adblocker-webextension/adblocker.ts#L631

**Comment by skunkfox** [comment] 2022-09-29 11:58
Hey! Just wanted to let you know I haven't forgotten about this. I ended up joining a friend on an impromptu trip to the Netherlands so I haven't been near my laptop much but I still plan to keep investigating this when I return in a week.

**Comment by skunkfox** [comment] 2022-10-23 00:54
> Great to hear that you're doing better. Thanks for looking into this issue, that's a great start. So at least we know that scriplets and styles are correctly returned for youtube.com. I think the next step would be to check that the injection in the page happens as expected. One way would be to wrap the scripts injected with some debugging code to see its effect in page. You could try something like this maybe? https://github.com/ghostery/adblocker/blob/master/packages/adblocker-webextension/adblocker.ts#L631

I have made a similar modification to adblocker-electron/adblocker.ts:

`  private injectScripts(sender: Electron.WebContents, script: string): void {
    let debugMarker;
    debugMarker = (text: string) =>
      `console.log('[ADBLOCKER-DEBUG-TEST]:', ${JSON.stringify(text)});`;

    const codeRunningInPage = `(function(){
      ${debugMarker('run scriptlets (executing in "page world")')}
      ${script}}
      )()`;

    const codeRunningInContentScript = `
    (function(code) {
        ${debugMarker('run injection wrapper (executing in "content script world")')}
        var script;
        try {
          script = document.createElement('script');
          script.appendChild(document.createTextNode(decodeURIComponent(code)));
          (document.head || document.documentElement).appendChild(script);
        } catch (ex) {
          console.error('Failed to run script', ex);
        }
        if (script) {
            if (script.parentNode) {
              script.parentNode.removeChild(script);
            }
            script.textContent = '';
        }
    })(\`${encodeURIComponent(codeRunningInPage)}\`);`;


    //console.log(codeRunningInContentScript);

    
    sender.executeJavaScript(codeRunningInContentScript);
  }`

When I load the YouTube link (as he first page I load) I see the attached output in the browser debug console.
![image_2022-10-22_19-46-26](https://user-images.githubusercontent.com/88281387/197367924-d05a938b-59df-4da0-9190-c9255f6bb856.png)

I'm not sure how helpful that is to you. As for the contents of the injected scripts they seem rather obfuscated and difficult to debug directly (at least for a JavaScript / TypeScript / Electron newb like myself). But I still want to help in any way I can, after all I use Vieb as my main browser.

Where can I go from here?

**Comment by remusao** [comment] 2022-10-23 08:32
Thanks @skunkfox, that is very useful. Now we know that the scripts that should be injected are injected. I checked with uBlock Origin's logger and and it seems to match:

![image](https://user-images.githubusercontent.com/1299873/197381693-7530fc43-b658-4408-b175-224bf6b38610.png)

Two things come to mind:
1. These scripts need to be injected in *any* frame of the page, so one thing we could also check is that it's also the case here with Electron (i.e. injecting both in main page document but also in all iframes). Maybe one way could be to check the we see these injected each multiple times (in the adblocker logs from Electron?) since that seems to be what to expect based on uBlock Origin's logger. After loading a YouTube page I can see (using `document.querySelectorAll('iframe')` in the page console dev tool) that there are 3 iframes so each of these should get the scripts.
2. Another issue which might be more tricky to check, is that from what I remember, the timing of injection matters a great deal on YouTube. Meaning that we should aim at injecting these scripts as quickly as possible in the page. If the ad has time to start loading before injection then it's too late to prevent it. Here we would need to see if we can perform the injection earlier. At the moment we have a round-trip to the page: https://github.com/ghostery/adblocker/blob/master/packages/adblocker-electron/adblocker.ts#L86
  a. The preload script is injected in the page (that might already be happening pretty late in the life-cycle of the frame; not entirely sure how Electron implements that)
  b. The preload script sends a message to main process to request injections https://github.com/ghostery/adblocker/blob/master/packages/adblocker-electron-preload/preload.ts#L15
  c. When this message is received by main process: https://github.com/ghostery/adblocker/blob/master/packages/adblocker-electron/adblocker.ts#L86 it then checks for things to inject and performs the injection here: https://github.com/ghostery/adblocker/blob/master/packages/adblocker-electron/adblocker.ts#L270

I suspect this is too slow. In the webextension adblocker for browsers we now have a way to detect new frames using the webNavigation listener from the main process and inject scripts earlier; avoiding a round-trip with the page. We should look for alternatives in Electron APIs. If there is a way to listen to an event for new pages or frames from the main process, then we could react quicker.

I see there are a bunch of events here: https://www.electronjs.org/docs/latest/api/web-contents#instance-events
We can experiment and check in which order they trigger, and what is the earliest point where we could perform the injection successfully.

**Comment by skunkfox** [comment] 2022-11-15 21:02
So I am somewhat skeptical that the scriplets are being injected into all iframes. For one, I see that there are three scripts getting injected and the content of each one is unique. I would expect to see multiple copies of each script getting injected, one for each iframe. Although I could well be wrong about this, maybe each iframe is supposed to receive a unique script?

I added some debug code to list additional iframe context:

```javascript
    // Some added debugging
    let frames = event.sender.mainFrame.frames;
    let name = event.sender.mainFrame.name;
    let url_holder = event.sender.mainFrame.url;

    console.log("[BEGIN DEBUG DUMP]");
    console.log("Name: ", name);
    console.log("Frames: ", frames);
    console.log("URL: ", url_holder);
    console.log("[END DEBUG DUMP]");

    // Inject custom stylesheets
    this.injectStyles(event.sender, styles);

    // Inject scriptlets
    for (const script of scripts) {
      console.log("INJECTING SCRIPLETS");
      this.injectScripts(event.sender, script);
    }
```

I get the following output:

`
[BEGIN DEBUG DUMP]
Name:  
Frames:  []
URL:  https://www.youtube.com/watch?v=-t9XZgk6kNY
[END DEBUG DUMP]
INJECTING SCRIPLETS
SCRIPT INJECTED
INJECTING SCRIPLETS
SCRIPT INJECTED
INJECTING SCRIPLETS
SCRIPT INJECTED
`

Now the source code for WebFrame says:
```javascript
    readonly frames: WebFrameMain[];
    /**
     * A `WebFrameMain[]` collection containing every frame in the subtree of `frame`,
     * including itself. This can be useful when traversing through all frames.
     *
     */
```

If the 'frames' attribute should include the main frame, I don't see why my console.log() calls don't show anything for it. I must be doing something wrong. Any tips?

**Comment by michael-dm** [comment] 2022-12-09 13:15
Hello guys, juste came across the same problem in my Electron app, first video loaded always gets ads. Did you have the time to look into it ? :)

**Comment by skunkfox** [comment] 2022-12-27 20:15
> Hello guys, juste came across the same problem in my Electron app, first video loaded always gets ads. Did you have the time to look into it ? :)

This is driving me insane. I am going to look back into it in the next few days. I'll coerce my friend who is more experienced with Javascript to help me.

@michael-dm Do you want to help me debug this? You have a Telegram or Discord or IRC or Matrix handle I can use to get in touch?

**Comment by skunkfox** [comment] 2023-01-14 23:25
So I recently tried to get back into this, with the latest code, same YouTube video. I am noticing some odd behavior, like I'm not even able to execute console.error using sender.executeJavaScript.

Here is why my injectScripts function looks like in adblocker-electron/adblocker.ts:

```
private injectScripts(sender: Electron.WebContents, script: string): void {
    /* I should be able to execute a console.log error mesage using sender.executeJavaScript. */

    const injection_wrapper = `(function(test_text) {
      console.error("Why can't I see this?");
      console.error(test_text);
    })(\`>> TEST TEXT\`);`

    console.error('DEBUG');
    console.error('DEBUG');
    console.error('DEBUG');
    sender.executeJavaScript(injection_wrapper);
    sender.executeJavaScript(script);
    console.error('DEBUG');
    console.error('DEBUG');
    console.error('DEBUG');
  }
```

And this is my output:
```
DEBUG
DEBUG
DEBUG
DEBUG
DEBUG
DEBUG
DEBUG
DEBUG
DEBUG
DEBUG
DEBUG
DEBUG
DEBUG
DEBUG
DEBUG
DEBUG
DEBUG
DEBUG
```

It's like injection_wrapper isn't getting executed at all.

**Comment by michael-dm** [comment] 2023-01-15 10:22
Hello @skunkfox, I made a repro of this bug on Electron Fiddle if it's helpful : 
https://gist.github.com/bf00689b195a6464b2f21fd6e9671595

You can add me on Discord here : Michaël#3536

**Comment by skunkfox** [comment] 2023-01-16 00:07
> Hello @skunkfox, I made a repro of this bug on Electron Fiddle if it's helpful : https://gist.github.com/bf00689b195a6464b2f21fd6e9671595
> 
> You can add me on Discord here : Michaël#3536

Great, I just started getting into this again this weekend.
Sent you a friend request. :)

**Comment by Araxeus** [comment] 2023-01-20 22:28
This also happens on https://www.npmjs.com/package/@cliqz/adblocker-puppeteer

Just start a puppeteer instance and open a tab or two on youtube.com and you will 100% get an ad
I've tested this dozens of times

**Comment by skunkfox** [comment] 2023-01-20 22:54
> This also happens on https://www.npmjs.com/package/@cliqz/adblocker-puppeteer
> 
> Just start a puppeteer instance and open a tab or two on youtube.com and you will 100% get an ad I've tested this dozens of times

Hey Ataxeus, I'm starting a debugging branch to work on this. (Not that I'm making much progress so far, right now I'm still trying to determine if the scriptlets are running in the correct frames). Do you have a Discord or Slack or Telegram? I'd be interested in group chatting with you and michael-dm and finally figuring this out.

**Comment by skunkfox** [comment] 2023-01-20 23:24
Okay, so strangely enough, ads stopped appearing on the old test video and I had to update it.

So, I've got this [debug repo](https://github.com/skunkfox/adblocker_debug) set up. You can clone it, then type 'yarn bootstrap' and 'yarn build' and 'yarn watch' in the root directory to build everything and re-build it on changes. Then cd to 'packages/adblocker-electron-example' and run 'npm start' to bring up an electron video to a page where YouTube shows an ad.

In the browser debug window you'll see some debug output I added to './adblocker-electron/adblocker.ts'.  Specifically I expect 'codeRunningInPage' and 'console.log('Current Frame:', sName);' to show me the name of the current frame. Nada. You'd think for how long I've had this bug open I would have figured this out by now but I have no experience with Electron and real life events keep pulling me away from this.

I suspect the problem has to do with what @remusao  [mentioned earlier ](https://github.com/ghostery/adblocker/issues/2757#issuecomment-1288051577), specifically point 1 that maybe the scriptlets aren't being injected multiple times, because right now it looks like each frame gets a unique scriptlet. (Or at least, when I log the scriptlets they are all unique). But it could be point 2 as well.

I'd appreciate any help for with this because I had having to switch to librewolf each time I visit YouTube.

**Comment by lanouettea** [comment] 2023-02-15 02:53
Any updates about this? I'm encountering the same issue with Ads not being blocked in YouTube videos in a project I am working on.

**Comment by skunkfox** [comment] 2023-02-15 04:52
> Any updates about this? I'm encountering the same issue with Ads not being blocked in YouTube videos in a project I am working on.

Sigh, no. I started a new job and the hours are crazy so I don't have much time to work on personal projects at the moment.

**Comment by DrRoot-github** [comment] 2023-03-25 02:54
Eventually, I realized that the problem was not the timing of injection, but how the filter was applied. First, in response to the theory that injection is too slow, I changed the timing of generating the DOM_MONITOR in adblock-electron-preload/preload.ts to start monitoring as quickly as possible without waiting for DOMContentLoaded. As a result, I also changed the way the observer is generated in adblocker-content/adblocker.ts to directly monitor window.document instead of window.document.documentElement (which is null until DOMContentLoaded occurs). This was also because µBlock origin was doing it this way. Even when viewed from the browser debugger, it seems certain that the monitoring is running before the DOM is constructed at the moment the YouTube page is opened. However, the initial advertisement was displayed (subsequent advertisements were blocked without any problems). 

https://github.com/ghostery/adblocker/commit/2bdb7adf02d910ec090929e95b8a6efe7a1fa135#diff-5d03f5bd9f056eb7923bbb2290260fbb59abc39509f7adef896da5dfa6113291
https://github.com/ghostery/adblocker/commit/2bdb7adf02d910ec090929e95b8a6efe7a1fa135#diff-fa7732f0df558ff692bf3fd4dbe1bdba016561216c37548ab5e6d29a33447285

For now, I'll continue investigating why we can't do the same thing as in μBlock. It's not necessarily an issue with the preload itself, so I'll keep looking into it.

**Comment by skunkfox** [comment] 2023-03-27 22:10
DrRoot, I see for some reason your comment was deleted, but I want you to know I really appreciate you looking into this.
You're fucking awesome dude.

**Comment by DrRoot-github** [comment] 2023-03-28 01:19
I'm sorry, but I have since researched more and now believe that my initial assessment was incorrect. As a result, I have retracted my comment to avoid confusion.

The code injected by the preload script during page load, called "inject script", is working correctly. The problem is with the injector, which is used for injection after the page has loaded, specifically with cosmetic filters.

The following specific cosmetic filter successfully blocks ads on the first load:
```
youtube.com, youtubekids.com, youtube-nocookie.com##+js(json-prune, [].playerResponse.adPlacements [].playerResponse.playerAds playerResponse.adPlacements playerResponse.playerAds adPlacements playerAds)
youtube.com, youtubekids.com, youtube-nocookie.com##+js(set, ytInitialPlayerResponse.adPlacements, undefined)
youtube.com, youtubekids.com, youtube-nocookie.com##+js(set, playerResponse.adPlacements, undefined)
```

If this filter is removed, ads will appear even in a uBlock environment. Therefore, remusao's assessment that script injection is not functioning properly is not entirely incorrect.

I'm currently investigating what is not working properly and how to fix it.

**Comment by DrRoot-github** [comment] 2023-03-30 14:18
https://github.com/ghostery/adblocker/pull/3162

Finally, I was able to successfully block the ads that appear on the initial load of YouTube. I changed the injection process to perform scriptlet injection without waiting for the DOMContentLoaded event to fire, and it seems to have worked. I'm not entirely sure if my approach is correct, but I went ahead and submitted a pull request. I apologize if I didn't follow the proper procedures.

**Comment by Araxeus** [comment] 2023-03-30 14:25
thank you @DrRoot-github this is awesome :)

**Closed** 2023-04-02 09:11 UTC

**Comment by Araxeus** [comment] 2023-04-02 16:56
I haven't tested it yet, but it looks like this fix hasn't been ported to Puppeteer ? only Electron?

See my comment above https://github.com/ghostery/adblocker/issues/2757#issuecomment-1399029414

**Comment by remusao** [comment] 2023-04-03 07:14
@Araxeus indeed, I had forgotten we also added a report of Puppeteer to this issue as it was initially opened for Electron. The fix required for Puppeteer will likely be platform-specific or impossible. This needs to be investigated separately. Would you mind creating a separate issue for that?

**Comment by Araxeus** [comment] 2023-04-03 08:53
Probably need to see if we could listen to another event here right?

https://github.com/ghostery/adblocker/blob/master/packages/adblocker-puppeteer/adblocker.ts#L71

**Comment by remusao** [comment] 2023-04-03 08:58
@Araxeus yes that seems like a good way to go, would you be able to experiment with this?

**Comment by Araxeus** [comment] 2023-04-03 09:00
I'll try to find some time to look into it this week. no promises tho ✌️

**Comment by skunkfox** [comment] 2023-04-08 02:17
You guys are all amazing. Thank you so much.

@DrRoot-github You are a hero.
