### ISSUE TITLE
URL containing too many tokens does not match

### ISSUE THREAD

**Issue by mjethani** [ghostery/adblocker#2189] opened 2021-08-25 17:24 UTC
Consider this very long URL from the request data set:

```
https://www.google-analytics.com/j/collect?v=1&_v=j92&a=393452224&t=pageview&_s=1&dl=https%3A%2F%2Fthechive.com%2F&ul=en-us&de=UTF-8&dt=An%20improbable%20hall%20of%20fame%20journey%20and%20the%201.000%20batting%20average%20(8%20Photos)%09%09%09%0A%09%09%0A%09%09%09%0A%09%09%09%09Actors%20you%20WON%E2%80%99T%20BELIEVE%20are%20turning%2060%20this%20year%20(16%20Photos)%09%09%09%0A%09%09%0A%09%09%09%0A%09%09%09%09Animals%20prove%20you%20can%20find%20friends%20in%20the%20most%20unlikely%20of%20places%20(22%20Photos)%09%09%09%0A%09%09%0A%09%09%09%0A%09%09%09%09A%20Bikini%20a%20day%20keeps%20the%20Bikini%20Doctor%20away%E2%80%A6%20right%3F%20(35%20Photos)%09%09%09%0A%09%09%0A%09%09%09%0A%09%09%09%09Daily%20Morning%20Awesomeness%20(40%20Photos)%09%09%09%0A%09%09%0A%09%09%09%0A%09%09%09%09Turns%20out%20marriage%20is%20a%20big%20f%40%23%25ing%20joke%20(31%20Photos)%09%09%09%0A%09%09%0A%09%09%09%0A%09%09%09%09Kids%20bring%20some%20crazy%20sh*t%20to%20show%20and%20tell%20(19%20GIFs)%09%09%09%0A%09%09%0A%09%09%09%0A%09%09%09%09Blazing%20hot%20Dutch%20runner%20Lieke%20Klaver%20won%20the%20Olympics%20(21%20photos)%09%09%09%0A%09%09%0A%09%09%09%0A%09%09%09%09Quentin%20Tarantino%20explains%20why%20he%E2%80%99ll%20NEVER%20give%20his%20mom%20a%20cent%20of%20his%20film%20money%09%09%09%0A%09%09%0A%09%09%09%0A%09%09%09%09Daily%20Afternoon%20Randomness%20(49%20Photos)%09%09%09%0A%09%09%0A%09%09%09%0A%09%09%09%09Keep%20calm%20and%20tug%20on%20(38%20Photos)%09%09%09%0A%09%09%0A%09%09%09%0A%09%09%09%09Some%20small%20hills%20are%20worth%20dying%20on%2C%20just%20ask%20these%20folks%20(20%20GIFs)%09%09%09%0A%09%09%0A%09%09%09%0A%09%09%09%09The%20best%20tweets%20from%20parents%20of%20all%20time%20last%20week%20(25%20photos)%09%09%09%0A%09%09%0A%09%09%09%0A%09%09%09%09Folks%20share%20memories%20of%20their%20fathers%20who%20passed%20away%20(21%20Photos)%09%09%09%0A%09%09%0A%09%09%09%0A%09%09%09%09Daily%20Morning%20Awesomeness%20(38%20Photos)%09%09%09%0A%09%09%0A%09%09%09%0A%09%09%09%09What%E2%80%99s%20the%20Worst%20Pain%20You%E2%80%99ve%20Ever%20Felt%3F%20(15%20GIFs)%09%09%09%0A%09%09%0A%09%09%09%0A%09%09%09%09All%20systems%20GO!%20Prepare%20for%20Liftoff%20in%203%E2%80%A62%E2%80%A61%E2%80%A6%20(45%20Photos)%09%09%09%0A%09%09%0A%09%09%09%0A%09%09%09%09Read%20Between%20the%20Tan%20Lines%20(35%20Photos)%09%09%09%0A%09%09%0A%09%09%09%0A%09%09%09%09My%20sweet%20Big%20Mouth%20Billy%20Bass%2C%20look%20what%20they%20did%20to%20you!%20(Video)%09%09%09%0A%09%09%0A%09%09%09%0A%09%09%09%09Weekend%20Afternoon%20Randomness%20(36%20Photos)%09%09%09%0A%09%09%0A%09%09%09%0A%09%09%09%09GIFs%20prove%3A%20Can%E2%80%99t%20out-Random%20the%20internet%20(25%20GIFs)%09%09%09%0A%09%09%0A%09%09%09%0A%09%09%09%09These%20male%20authors%20prove%20they%20know%20nothing%20about%20women%E2%80%99s%20bodies%20(31%20Photos)%09%09%09%0A%09%09%0A%09%09%09%0A%09%09%09%09Nice%20Design%20Work%20Ya%20Absolute%20Prick!%20(23%20Photos)%09%09%09%0A%09%09%0A%09%09%09%0A%09%09%09%09Upon%20closer%20inspection%20HOLY%20S***!%20(35%20Photos)%09%09%09%0A%09%09%0A%09%09%09%0A%09%09%09%09Weekend%20Morning%20Awesomeness%20(37%20photos)&sd=24-bit&sr=800x600&vp=800x600&je=0&_u=YEBAAAABAAAAAC~&jid=331000972&gjid=1930197999&cid=827252379.1628628622&tid=UA-6481362-1&_gid=1175243576.1628628622&_r=1&gtm=2wg891P83WPK&cg2=homepage&cd2=&cd3=homepage&cd4=&cd5=&cd13=C_JS%3A%5Bobject%20Object%5Dundefined%2CmetaId%3Ano%2CbodyPostId%3Ano&z=388502388
```

This URL contains too many tokens.

### Expected result

The filter `/collect?*&cid=` should match this URL.

### Actual result

The filter `/collect?*&cid=` does not match this URL.

### More details

Similar issues in other ad blockers:

* uBlock Origin: https://github.com/uBlockOrigin/uBlock-issues/issues/1207
* Brave: https://github.com/brave/adblock-rust/issues/183

Discussion: https://github.com/cliqz-oss/adblocker/pull/2125#issuecomment-896699694

**Comment by remusao** [comment] 2022-05-22 09:45
@mjethani I looked into this and could not reproduce the issue. I was able to find a match with the above rule in the current version of `@cliqz/ablocker` but also with the URL from the uBlock Origin issue linked. So I am not sure this is an issue at the moment. I will be closing this issue, if you have time to look again and find that the issue still exists, please feel free to reopen.

**Closed by remusao** 2022-05-22 09:45 UTC
